using System.IO;
using System.Text.Json;
using Xunit;

namespace Perch.Tests;

/// The board file format. Two properties matter more than any single assertion
/// here, and both have a test that would fail loudly if they broke:
///
///   1. board.md must READ WELL to an agent that knows nothing about Perch —
///      real repo-relative paths, ordinary markdown, no custom syntax it would
///      have to be taught.
///   2. Perch must never overwrite a board it could not parse. The layout
///      block is the whole content; saving over an unreadable one destroys it.
public class BoardStoreTests
{
    private static string TempRepo()
    {
        var dir = Path.Combine(Path.GetTempPath(), "perch-boardtest-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static BoardDoc Sample()
    {
        var doc = new BoardDoc { Title = "login bug" };
        doc.Nodes.Add(new BoardNode
        {
            Id = "n1", Kind = "path", Ref = "src/auth/session.ts",
            Text = "where the cookie is set", X = 268, Y = 28,
        });
        doc.Nodes.Add(new BoardNode
        {
            Id = "n2", Kind = "image", Ref = "assets/login-broken.png",
            Text = "the failure state", X = 16, Y = 132,
        });
        doc.Nodes.Add(new BoardNode
        {
            Id = "n3", Kind = "url", Ref = "refs/oauth.md",
            Source = "https://example.com/oauth", FetchedUtc = "2026-07-29", X = 16, Y = 16,
        });
        doc.Nodes.Add(new BoardNode
        {
            Id = "n4", Kind = "note",
            Text = "Session cookie stays HttpOnly.", X = 16, Y = 356,
        });
        doc.Links.Add(new BoardLink { From = "n2", To = "n1", Label = "shows" });
        return doc;
    }

    // ---- round trip -------------------------------------------------------

    [Fact]
    public void Render_ThenExtract_RoundTripsEveryField()
    {
        var md = BoardStore.Render(Sample());
        var json = BoardStore.ExtractLayout(md);
        Assert.NotNull(json);

        var back = JsonSerializer.Deserialize(json!, BoardJsonContext.Default.BoardDoc)!;
        Assert.Equal("login bug", back.Title);
        Assert.Equal(4, back.Nodes.Count);
        var img = back.Find("n2")!;
        Assert.Equal("image", img.Kind);
        Assert.Equal("assets/login-broken.png", img.Ref);
        Assert.Equal("the failure state", img.Text);
        Assert.Equal((16d, 132d), (img.X, img.Y));
        var url = back.Find("n3")!;
        Assert.Equal("https://example.com/oauth", url.Source);
        Assert.Equal("2026-07-29", url.FetchedUtc);
        Assert.Single(back.Links);
        Assert.Equal(("n2", "n1", "shows"), (back.Links[0].From, back.Links[0].To, back.Links[0].Label));
    }

    [Fact]
    public void Render_BodyIsPlainMarkdownAnAgentCanRead()
    {
        var md = BoardStore.Render(Sample());

        // Headings an agent can navigate, and the paths as literal text.
        Assert.Contains("# login bug", md);
        Assert.Contains("## Files", md);
        Assert.Contains("`src/auth/session.ts`", md);
        Assert.Contains("## Images", md);
        Assert.Contains("`assets/login-broken.png`", md);
        Assert.Contains("## Notes", md);
        Assert.Contains("Session cookie stays HttpOnly.", md);

        // A cached page with no provenance is a page not to trust — the source
        // URL and the fetch date must both survive into the prose.
        Assert.Contains("https://example.com/oauth", md);
        Assert.Contains("2026-07-29", md);

        // Every path in the body is repo-relative; an absolute one would only
        // make sense on the machine that wrote it.
        Assert.DoesNotContain(":\\", md);
    }

    /// Golden file. The prose body is the API an agent consumes, so a change to
    /// it is a change to a contract with something that cannot be recompiled.
    /// If this fails, decide deliberately whether the new shape still reads as
    /// an ordinary document, then update the expectation.
    [Fact]
    public void Render_BodyMatchesTheAgreedShape()
    {
        var body = BodyOf(BoardStore.Render(Sample())).Replace("\r\n", "\n");
        const string expected =
            "<!-- perch:board v1 - generated by Perch. The layout block at the end of\n" +
            "     this file is authoritative; edits to the prose above it are replaced\n" +
            "     the next time the board changes. -->\n" +
            "\n" +
            "# login bug\n" +
            "\n" +
            "## Files\n" +
            "- `src/auth/session.ts` - where the cookie is set\n" +
            "\n" +
            "## Images\n" +
            "- `assets/login-broken.png` - the failure state\n" +
            "\n" +
            "## References\n" +
            "- `refs/oauth.md` - fetched 2026-07-29 from https://example.com/oauth\n" +
            "\n" +
            "## Notes\n" +
            "- Session cookie stays HttpOnly.\n" +
            "\n" +
            "## Related\n" +
            "- `assets/login-broken.png` shows `src/auth/session.ts`\n" +
            "\n";
        Assert.Equal(expected, body);
    }

    [Fact]
    public void Render_EmptyBoardSaysSoRatherThanRenderingNothing()
    {
        var md = BoardStore.Render(new BoardDoc { Title = "fresh" });
        Assert.Contains("# fresh", md);
        Assert.Contains("Nothing on this board yet.", md);
        Assert.NotNull(BoardStore.ExtractLayout(md));   // still round-trips
    }

    [Fact]
    public void Render_OmitsSectionsWithNoNodes()
    {
        var doc = new BoardDoc { Title = "notes only" };
        doc.Nodes.Add(new BoardNode { Id = "n1", Kind = "note", Text = "just this" });
        var md = BoardStore.Render(doc);
        Assert.Contains("## Notes", md);
        Assert.DoesNotContain("## Files", md);
        Assert.DoesNotContain("## Images", md);
        Assert.DoesNotContain("## References", md);
        Assert.DoesNotContain("## Related", md);
    }

    [Fact]
    public void Render_DanglingLinkIsDroppedNotRenderedAsBrokenProse()
    {
        var doc = new BoardDoc { Title = "x" };
        doc.Nodes.Add(new BoardNode { Id = "n1", Kind = "note", Text = "kept" });
        doc.Links.Add(new BoardLink { From = "n1", To = "n99", Label = "points at" });
        var md = BoardStore.Render(doc);
        Assert.DoesNotContain("n99", BodyOf(md));
        Assert.DoesNotContain("points at", BodyOf(md));
    }

    [Fact]
    public void Render_MultilineNoteCollapsesSoTheListStaysAList()
    {
        var doc = new BoardDoc { Title = "x" };
        doc.Nodes.Add(new BoardNode { Id = "n1", Kind = "note", Text = "line one\r\nline  two" });
        var body = BodyOf(BoardStore.Render(doc));
        Assert.Contains("- line one line two", body);
        // One bullet, not two.
        Assert.Equal(1, body.Split("\n- ").Length - 1);
    }

    // ---- layout extraction ------------------------------------------------

    [Fact]
    public void ExtractLayout_IgnoresTheMarkerAppearingInsideANote()
    {
        // A note whose text quotes the marker must not shadow the real block.
        var doc = new BoardDoc { Title = "x" };
        doc.Nodes.Add(new BoardNode { Id = "n1", Kind = "note", Text = "see <!-- perch:layout in the docs" });
        var md = BoardStore.Render(doc);
        var json = BoardStore.ExtractLayout(md);
        Assert.NotNull(json);
        var back = JsonSerializer.Deserialize(json!, BoardJsonContext.Default.BoardDoc)!;
        Assert.Single(back.Nodes);
    }

    [Fact]
    public void ExtractLayout_ReturnsNullWhenThereIsNoBlock()
    {
        Assert.Null(BoardStore.ExtractLayout("# just a markdown file\n\nno block here\n"));
        Assert.Null(BoardStore.ExtractLayout("<!-- perch:layout {\"v\":1}"));   // unterminated
    }

    // ---- the refuse-to-clobber guarantee ----------------------------------

    [Fact]
    public void Open_UnparseableBoard_IsUnreadableAndSaveLeavesTheFileAlone()
    {
        var repo = TempRepo();
        try
        {
            var store = BoardStore.Create(repo, "login bug");
            var path = store.MarkdownPath;

            // Corrupt the layout block the way a bad merge or a truncated write
            // would, leaving the prose intact.
            File.WriteAllText(path, "# login bug\n\n## Notes\n- something valuable\n\n<!-- perch:layout\n{not json\n-->\n");
            var original = File.ReadAllText(path);

            var reopened = BoardStore.Open(store.Dir)!;
            Assert.False(reopened.Readable);
            Assert.NotEmpty(reopened.Problem);

            // The whole point: saving must NOT destroy what we could not read.
            reopened.Doc.Nodes.Add(new BoardNode { Id = "n1", Kind = "note", Text = "new" });
            reopened.Save();
            Assert.Equal(original, File.ReadAllText(path));
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    [Fact]
    public void Open_BoardFromANewerVersion_IsRefusedRatherThanTruncated()
    {
        var repo = TempRepo();
        try
        {
            var store = BoardStore.Create(repo, "future");
            File.WriteAllText(store.MarkdownPath,
                "# future\n\n<!-- perch:layout\n{\"v\":99,\"title\":\"future\",\"nodes\":[]}\n-->\n");
            var reopened = BoardStore.Open(store.Dir)!;
            Assert.False(reopened.Readable);
            Assert.Contains("newer version", reopened.Problem);
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    [Fact]
    public void Open_MissingFolder_ReturnsNullSoTheePaneCanSayWhy()
    {
        Assert.Null(BoardStore.Open(Path.Combine(Path.GetTempPath(), "perch-no-such-board-" + Guid.NewGuid().ToString("N"))));
        Assert.Null(BoardStore.Open(""));
    }

    [Fact]
    public void Open_FolderWithNoIndexYet_IsEmptyNotBroken()
    {
        var repo = TempRepo();
        try
        {
            var dir = Path.Combine(repo, ".perch", "boards", "bare");
            Directory.CreateDirectory(dir);
            var store = BoardStore.Open(dir)!;
            Assert.True(store.Readable);
            Assert.Empty(store.Doc.Nodes);
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    // ---- creation ---------------------------------------------------------

    [Fact]
    public void Create_WritesTheSelfIgnoringGitignore()
    {
        var repo = TempRepo();
        try
        {
            BoardStore.Create(repo, "login bug");
            var ignore = Path.Combine(repo, ".perch", ".gitignore");
            Assert.True(File.Exists(ignore));
            // "*" is what makes `git ls-files --others --exclude-standard` skip
            // the whole tree, which is what keeps fetched refs out of the
            // agent's LOC chip. Without this line the feature inflates diffs.
            Assert.Contains("*", File.ReadAllText(ignore));
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    [Fact]
    public void Create_DoesNotTouchTheUsersOwnGitignore()
    {
        var repo = TempRepo();
        try
        {
            var users = Path.Combine(repo, ".gitignore");
            File.WriteAllText(users, "node_modules/\n");
            BoardStore.Create(repo, "b");
            Assert.Equal("node_modules/\n", File.ReadAllText(users));
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    [Fact]
    public void Create_SecondBoardWithTheSameTitleGetsItsOwnFolder()
    {
        var repo = TempRepo();
        try
        {
            var a = BoardStore.Create(repo, "login bug");
            var b = BoardStore.Create(repo, "login bug");
            Assert.NotEqual(a.Dir, b.Dir);
            Assert.EndsWith("login-bug", a.Dir);
            Assert.EndsWith("login-bug-2", b.Dir);
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    [Fact]
    public void Create_TitleThatSlugifiesToNothingStillGetsAFolder()
    {
        var repo = TempRepo();
        try
        {
            var store = BoardStore.Create(repo, "???");
            Assert.True(Directory.Exists(store.Dir));
            Assert.EndsWith("board", store.Dir);
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    [Fact]
    public void CreateThenOpen_SurvivesTheDiskRoundTrip()
    {
        var repo = TempRepo();
        try
        {
            var store = BoardStore.Create(repo, "login bug");
            store.Doc.Nodes.Add(new BoardNode { Id = "n1", Kind = "note", Text = "a note", X = 8, Y = 8 });
            store.Save();

            var back = BoardStore.Open(store.Dir)!;
            Assert.True(back.Readable);
            Assert.Equal("login bug", back.Doc.Title);
            Assert.Single(back.Doc.Nodes);
            Assert.Equal("a note", back.Doc.Nodes[0].Text);
        }
        finally { Directory.Delete(repo, recursive: true); }
    }

    // ---- id allocation ----------------------------------------------------

    [Fact]
    public void NextId_DoesNotReuseAnIdAfterARemoval()
    {
        var doc = new BoardDoc();
        doc.Nodes.Add(new BoardNode { Id = "n1" });
        doc.Nodes.Add(new BoardNode { Id = "n2" });
        doc.Nodes.RemoveAll(n => n.Id == "n1");
        // Counting would give "n2" and collide with the survivor; scanning
        // gives n3. Links point at ids, so a collision silently re-targets one.
        Assert.Equal("n3", doc.NextId());
    }

    [Fact]
    public void NextId_OnAnEmptyBoardIsN1() => Assert.Equal("n1", new BoardDoc().NextId());

    // ---- path containment -------------------------------------------------

    [WindowsFact]
    public void ToRepoRelative_InsideTheRepoBecomesAForwardSlashPath()
    {
        Assert.Equal("src/auth/session.ts",
            BoardStore.ToRepoRelative(@"C:\dev\perch", @"C:\dev\perch\src\auth\session.ts"));
        // Trailing separator on the root must not change the answer.
        Assert.Equal("a/b.txt", BoardStore.ToRepoRelative(@"C:\dev\perch\", @"C:\dev\perch\a\b.txt"));
    }

    [UnixFact]
    public void ToRepoRelative_InsideTheRepoBecomesAForwardSlashPath_Unix()
    {
        Assert.Equal("src/auth/session.ts",
            BoardStore.ToRepoRelative("/dev/perch", "/dev/perch/src/auth/session.ts"));
        Assert.Equal("a/b.txt", BoardStore.ToRepoRelative("/dev/perch/", "/dev/perch/a/b.txt"));
    }

    [Fact]
    public void ToRepoRelative_RefusesEscapesAndOutsiders()
    {
        // Traversal that normalizes back out of the repo.
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", @"C:\dev\perch\..\secrets\id_rsa"));
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", @"C:\dev\perch\a\..\..\b.txt"));
        // A sibling directory that shares the root's prefix.
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", @"C:\dev\perch-other\x.txt"));
        // Somewhere else entirely.
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", @"C:\Users\me\.ssh\id_rsa"));
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", @"D:\elsewhere\x"));
    }

    [WindowsFact]
    public void ToRepoRelative_NormalizesBeforeComparingSoDotSegmentsCannotSneakPast()
    {
        // "a/../b.txt" is inside; the naive string check would keep the "..".
        Assert.Equal("b.txt", BoardStore.ToRepoRelative(@"C:\dev\perch", @"C:\dev\perch\a\..\b.txt"));
    }

    [UnixFact]
    public void ToRepoRelative_NormalizesBeforeComparing_Unix()
    {
        Assert.Equal("b.txt", BoardStore.ToRepoRelative("/dev/perch", "/dev/perch/a/../b.txt"));
    }

    [Fact]
    public void ToRepoRelative_HandlesGarbageWithoutThrowing()
    {
        Assert.Null(BoardStore.ToRepoRelative("", @"C:\x"));
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", ""));
        Assert.Null(BoardStore.ToRepoRelative(@"C:\dev\perch", "   "));
    }

    // Body = everything before the layout block, i.e. what a reader sees.
    private static string BodyOf(string md)
    {
        var i = md.IndexOf("<!-- perch:layout", StringComparison.Ordinal);
        return i < 0 ? md : md[..i];
    }
}
