using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Perch;

/// Reads and writes a board folder. Pure file mechanics — resolving what the
/// user pasted into an artifact lives elsewhere; this only knows how to turn a
/// BoardDoc into board.md and back.
///
/// ## The file format, and why it is shaped this way
///
/// board.md is clean, readable markdown with ONE trailing HTML comment holding
/// the authoritative JSON. The prose body is GENERATED from that JSON. So:
///
///   - An agent (or a human, or GitHub) reading board.md sees an ordinary
///     document with real repo-relative paths in it. Nothing to teach, no new
///     format to parse, no tool required.
///   - Perch reads exactly one thing — the layout block — so the parser is
///     total and trivial rather than a markdown implementation.
///
/// The cost is stated in the file's own header: hand-edits to the prose are
/// overwritten on the next save. If that turns out to matter, the upgrade is
/// to move geometry into per-node comments and make the body authoritative.
///
/// ## Refusing to save over something we could not read
///
/// If the layout block is missing or malformed, Load returns a store with
/// Readable == false and Save becomes a no-op. A board whose index we cannot
/// parse is a board whose contents we would otherwise DESTROY on the next
/// write — better to surface the breakage in the pane and leave the file
/// alone.
internal sealed class BoardStore
{
    /// Marks the start of the authoritative block. Also the version tripwire:
    /// a future format bumps this and old builds fail to parse (and therefore
    /// refuse to save) rather than silently truncating a newer board.
    private const string LayoutOpen = "<!-- perch:layout";
    private const string LayoutClose = "-->";

    private const string HeaderComment =
        "<!-- perch:board v1 - generated by Perch. The layout block at the end of\n" +
        "     this file is authoritative; edits to the prose above it are replaced\n" +
        "     the next time the board changes. -->";

    /// Absolute path to the board folder.
    public string Dir { get; }

    /// False when board.md exists but could not be parsed. Save() refuses.
    public bool Readable { get; private set; } = true;

    /// Why it is unreadable, for the pane's error state. Empty when fine.
    public string Problem { get; private set; } = "";

    public BoardDoc Doc { get; private set; } = new();

    public string MarkdownPath => Path.Combine(Dir, "board.md");
    public string AssetsDir => Path.Combine(Dir, "assets");
    public string RefsDir => Path.Combine(Dir, "refs");

    private BoardStore(string dir) { Dir = dir; }

    // ---- creation ---------------------------------------------------------

    /// Create a new board under `repoRoot`, returning its store. The slug is
    /// derived from the title and de-duplicated with a numeric suffix the way
    /// Worktree.PathFor does, so two boards called "login bug" coexist.
    public static BoardStore Create(string repoRoot, string title)
    {
        var slug = GitProc.Slugify(title);
        if (slug.Length == 0) slug = "board";

        var boardsRoot = Path.Combine(repoRoot, ".perch", "boards");
        var dir = Path.Combine(boardsRoot, slug);
        for (var i = 2; Directory.Exists(dir) && i < 100; i++)
            dir = Path.Combine(boardsRoot, $"{slug}-{i}");

        Directory.CreateDirectory(dir);
        EnsureGitIgnored(repoRoot);

        var store = new BoardStore(dir);
        store.Doc = new BoardDoc { Title = title };
        store.Save();
        return store;
    }

    /// Write `.perch/.gitignore` containing "*" if it isn't there already.
    ///
    /// This is not tidiness. GitProc.UntrackedStatsAsync enumerates with
    /// `git ls-files --others --exclude-standard`, which honors nested ignore
    /// files — so without this, every fetched reference and pasted screenshot
    /// folds its line count into the pane's `linesAdded`. That is exactly the
    /// regression UntrackedBaseline exists to prevent (see Session.cs: "a repo
    /// with old scrape output wore '+90k' on an agent that had touched
    /// nothing"). It also keeps screenshots, which can carry secrets, from
    /// being committed by accident.
    ///
    /// The user's own .gitignore is never touched. Deleting ours is the opt-in
    /// to tracking boards.
    public static void EnsureGitIgnored(string repoRoot)
    {
        var path = Path.Combine(repoRoot, ".perch", ".gitignore");
        if (File.Exists(path)) return;
        try
        {
            AtomicFile.WriteAllText(path,
                "# Perch boards: local staging context, not source.\n" +
                "# Delete this file if you want boards tracked in git.\n" +
                "*\n");
        }
        catch (Exception ex) { Log.Error("BoardStore.EnsureGitIgnored", ex); }
    }

    // ---- load / save ------------------------------------------------------

    /// Open an existing board folder. Returns null if the folder is gone —
    /// the caller shows "this board's folder is missing" rather than an empty
    /// grid, which would look identical to a board you simply hadn't filled in
    /// yet.
    public static BoardStore? Open(string dir)
    {
        if (string.IsNullOrWhiteSpace(dir) || !Directory.Exists(dir)) return null;
        var store = new BoardStore(dir);
        store.Load();
        return store;
    }

    private void Load()
    {
        var path = MarkdownPath;
        if (!File.Exists(path))
        {
            // A folder with no index yet is empty, not broken.
            Doc = new BoardDoc { Title = Path.GetFileName(Dir) };
            return;
        }
        string text;
        try { text = File.ReadAllText(path); }
        catch (Exception ex)
        {
            Log.Error("BoardStore.Read", ex);
            Fail("The board's index could not be read.");
            return;
        }

        var json = ExtractLayout(text);
        if (json == null) { Fail("The board's index is missing its layout block."); return; }

        try
        {
            var doc = JsonSerializer.Deserialize(json, BoardJsonContext.Default.BoardDoc);
            if (doc == null) { Fail("The board's index could not be parsed."); return; }
            if (doc.V > 1) { Fail($"This board was written by a newer version of Perch (v{doc.V})."); return; }
            doc.Nodes ??= new();
            doc.Links ??= new();
            if (string.IsNullOrEmpty(doc.Title)) doc.Title = Path.GetFileName(Dir);
            Doc = doc;
        }
        catch (Exception ex)
        {
            Log.Error("BoardStore.Parse", ex);
            Fail("The board's index could not be parsed.");
        }
    }

    private void Fail(string problem)
    {
        Readable = false;
        Problem = problem;
        Doc = new BoardDoc { Title = Path.GetFileName(Dir) };
    }

    /// Pull the JSON out of the trailing `<!-- perch:layout … -->` comment.
    /// Uses LastIndexOf so a note whose text happens to contain the marker
    /// can't shadow the real block.
    internal static string? ExtractLayout(string markdown)
    {
        var open = markdown.LastIndexOf(LayoutOpen, StringComparison.Ordinal);
        if (open < 0) return null;
        var start = open + LayoutOpen.Length;
        var close = markdown.IndexOf(LayoutClose, start, StringComparison.Ordinal);
        if (close < 0) return null;
        return markdown[start..close].Trim();
    }

    public void Save()
    {
        if (!Readable)
        {
            // Refusing here is the whole safety property — see the class doc.
            Log.Info("BoardStore.Save.refused", $"unreadable board at {Dir}");
            return;
        }
        try { AtomicFile.WriteAllText(MarkdownPath, Render(Doc)); }
        catch (Exception ex) { Log.Error("BoardStore.Save", ex); }
    }

    // ---- rendering --------------------------------------------------------

    /// Turn a BoardDoc into board.md. Pure and total so it can be unit-tested
    /// without touching disk.
    internal static string Render(BoardDoc doc)
    {
        var sb = new StringBuilder();
        sb.Append(HeaderComment).Append("\n\n");
        sb.Append("# ").Append(string.IsNullOrWhiteSpace(doc.Title) ? "board" : doc.Title.Trim()).Append("\n");

        if (doc.Nodes.Count == 0)
        {
            sb.Append("\nNothing on this board yet.\n");
        }
        else
        {
            Section(sb, doc, "Files", BoardNodeKind.Path);
            Section(sb, doc, "Images", BoardNodeKind.Image);
            Section(sb, doc, "References", BoardNodeKind.Url);
            Section(sb, doc, "Notes", BoardNodeKind.Note);
            Related(sb, doc);
        }

        sb.Append('\n').Append(LayoutOpen).Append('\n');
        sb.Append(JsonSerializer.Serialize(doc, BoardJsonContext.Default.BoardDoc));
        sb.Append('\n').Append(LayoutClose).Append('\n');
        return sb.ToString();
    }

    private static void Section(StringBuilder sb, BoardDoc doc, string heading, BoardNodeKind kind)
    {
        var name = KindName(kind);
        var rows = doc.Nodes.Where(n => n.Kind == name).ToList();
        if (rows.Count == 0) return;

        sb.Append("\n## ").Append(heading).Append('\n');
        foreach (var n in rows)
        {
            var caption = OneLine(n.Text);
            if (kind == BoardNodeKind.Note)
            {
                // A note has no artifact, so the text IS the row.
                sb.Append("- ").Append(caption.Length > 0 ? caption : "(empty note)").Append('\n');
                continue;
            }
            sb.Append("- `").Append(n.Ref ?? "?").Append('`');
            if (caption.Length > 0) sb.Append(" - ").Append(caption);
            if (kind == BoardNodeKind.Url && !string.IsNullOrEmpty(n.Source))
            {
                sb.Append(caption.Length > 0 ? " (" : " - ");
                if (!string.IsNullOrEmpty(n.FetchedUtc)) sb.Append("fetched ").Append(n.FetchedUtc).Append(" from ");
                else sb.Append("from ");
                sb.Append(n.Source);
                if (caption.Length > 0) sb.Append(')');
            }
            sb.Append('\n');
        }
    }

    private static void Related(StringBuilder sb, BoardDoc doc)
    {
        if (doc.Links.Count == 0) return;
        sb.Append("\n## Related\n");
        foreach (var l in doc.Links)
        {
            var a = Label(doc, l.From);
            var b = Label(doc, l.To);
            if (a == null || b == null) continue;   // dangling link, drop it
            var verb = OneLine(l.Label);
            sb.Append("- ").Append(a).Append(' ')
              .Append(verb.Length > 0 ? verb : "relates to").Append(' ').Append(b).Append('\n');
        }
    }

    /// How a node is named in prose: its artifact path if it has one, else a
    /// short quote of its text so a "Related" line reads as a sentence.
    private static string? Label(BoardDoc doc, string id)
    {
        var n = doc.Find(id);
        if (n == null) return null;
        if (!string.IsNullOrEmpty(n.Ref)) return "`" + n.Ref + "`";
        var t = OneLine(n.Text);
        if (t.Length == 0) return "a note";
        return "\"" + (t.Length > 48 ? t[..48].TrimEnd() + "…" : t) + "\"";
    }

    /// Collapse to a single line. Newlines in a markdown list item would break
    /// the list; the full text is always in the layout block anyway.
    internal static string OneLine(string? s)
    {
        if (string.IsNullOrWhiteSpace(s)) return "";
        var flat = s.Replace("\r", " ").Replace("\n", " ").Trim();
        while (flat.Contains("  ")) flat = flat.Replace("  ", " ");
        return flat;
    }

    // ---- path containment -------------------------------------------------

    /// Turn an absolute path into one relative to `repoRoot`, using forward
    /// slashes, or null if it escapes the repo.
    ///
    /// Containment is the security property here, not a nicety: board.md is
    /// handed to an agent as a list of things to open, so a path that resolves
    /// outside the project (via "..", a symlinked parent, or a bare
    /// "C:\Users\me\.ssh\id_rsa") would be an invitation to read it. Compare
    /// full paths AFTER GetFullPath normalizes away "." and ".." rather than
    /// string-matching the input, which "a/../../b" defeats.
    ///
    /// Returns null rather than throwing — callers surface "that file is
    /// outside this project" to the user.
    public static string? ToRepoRelative(string repoRoot, string absolutePath)
    {
        if (string.IsNullOrWhiteSpace(repoRoot) || string.IsNullOrWhiteSpace(absolutePath))
            return null;
        string root, full;
        try
        {
            root = Path.GetFullPath(repoRoot).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            full = Path.GetFullPath(absolutePath);
        }
        catch { return null; }   // malformed path (bad chars, too long, …)

        if (full.Length == root.Length)
            return string.Equals(full, root, StringComparison.OrdinalIgnoreCase) ? "" : null;
        if (full.Length < root.Length + 2) return null;
        if (!full.StartsWith(root, StringComparison.OrdinalIgnoreCase)) return null;
        // Require a separator at the boundary so "C:\repo-other\x" doesn't
        // pass as being inside "C:\repo".
        var sep = full[root.Length];
        if (sep != Path.DirectorySeparatorChar && sep != Path.AltDirectorySeparatorChar) return null;

        return full[(root.Length + 1)..].Replace('\\', '/');
    }

    public static string KindName(BoardNodeKind k) => k switch
    {
        BoardNodeKind.Note => "note",
        BoardNodeKind.Path => "path",
        BoardNodeKind.Image => "image",
        BoardNodeKind.Url => "url",
        _ => "note",
    };
}
